import matplotlib.pyplot as plt
import keras
from keras.models import Sequential, Model
from keras.layers import Dense
from keras.preprocessing.image import ImageDataGenerator
import matplotlib.pyplot as plt
from keras import optimizers
from keras.callbacks import EarlyStopping,ModelCheckpoint, ReduceLROnPlateau
from keras_vggface.vggface import VGGFace
from keras.layers import Conv2D, MaxPooling2D, Activation, Dropout, Flatten, Dense, BatchNormalization
from keras.engine import Model
from keras.layers import Input
import tensorflow as tf
import cv2
from tqdm import tqdm
import os
import numpy as np
from sklearn.metrics import confusion_matrix
from keras.utils import plot_model

config = tf.ConfigProto()
config.gpu_options.allow_growth = True
tf.keras.backend.set_session(tf.Session(config=config))


train_data_dir = 'age_dataset_2'

input_shape = 256
batch_size = 1
num_classes = 8
epochs = 1
# num_of_test_samples = 1581

def random_crop(img, random_crop_size):
    # Note: image_data_format is 'channel_last'
    assert img.shape[2] == 3
    height, width = img.shape[0], img.shape[1]
    dy, dx = random_crop_size
    x = np.random.randint(0, width - dx + 1)
    y = np.random.randint(0, height - dy + 1)
    return img[y:(y+dy), x:(x+dx), :]


def crop_generator(batches, crop_length):
    """Take as input a Keras ImageGen (Iterator) and generate random
    crops from the image batches generated by the original iterator.
    """
    while True:
        batch_x, batch_y = next(batches)
        batch_crops = np.zeros((batch_x.shape[0], crop_length, crop_length, 3))
        for i in range(batch_x.shape[0]):
            batch_crops[i] = random_crop(batch_x[i], (crop_length, crop_length))
        yield (batch_crops, batch_y)

train_gen = ImageDataGenerator(
    rescale = 1./255,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    validation_split=0.2,
   )


train_batches = train_gen.flow_from_directory(
    train_data_dir,
    target_size=(input_shape,input_shape),
    batch_size=batch_size,
    class_mode='categorical',
    subset='training')

validation_batches = train_gen.flow_from_directory(
    train_data_dir, # same directory as training data
    target_size=(input_shape, input_shape),
    batch_size=batch_size,
    class_mode='categorical',
    subset='validation')

# train_crops = crop_generator(train_batches, 224)
# validation_crops = crop_generator(validation_batches, 224)

vggface = VGGFace(model="vgg16", include_top= True, pooling='avg')

# model = Sequential()
# for i in range(len(vgg_features.layers) - 4):
#     model.add(vgg_features.layers[i])
#
# for layer in vgg_features.layers[:-5]:
#     layer.trainable = False
model = Sequential()
for i in range(len(vggface.layers)):
    model.add(vggface.layers[i])


# for layer in vgg_features.layers[150:]:
#     sep = '                 ' [len(layer.name)-149:]
#     print(layer.name, sep, layer.trainable)
    # layer.trainable = True

# top_model = Sequential()
# # model.add(vgg_features.layers[:170])
# top_model.add(Flatten())
# top_model.add(Dense(1000, activation='relu'))
# top_model.add(Dropout(0.5))
# top_model.add(Dense(100, activation='relu'))
# top_model.add(Dropout(0.5))
# top_model.add(Dense(8, activation='softmax'))
# # print(model.summary())
#
# model.add(top_model)
#
# for layer in model.layers[:170]:
#     layer.trainable = False

# print(vggface.summary())



# model.add(vgg_features.layers)
#
# model.add(Flatten())
# model.add(Dense(1000,activation='relu'))
# model.add(Dropout(0.5))
# model.add(Dense(100,activation='relu'))
# model.add(Dense(8, activation='softmax'))
#
# model.compile(optimizer=optimizers.Adam(lr=0.01), loss='categorical_crossentropy',
#               metrics=['acc'])
#
# checkpoint = ModelCheckpoint('weight.hdf5', monitor='val_loss', save_best_only=True)
# reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.1,
#                               patience=2, min_lr=0.001, verbose=1)
# early_stopping_monitor=EarlyStopping(patience=30, verbose=1)
#
# training = model.fit_generator(train_crops, validation_data=validation_crops,
#                                steps_per_epoch = train_batches.samples // batch_size, epochs=epochs,
#                                validation_steps = validation_batches.samples // batch_size,
#                                callbacks=[checkpoint, early_stopping_monitor])
#
# model.save('model_age.h5')
#
#
# plt.plot(training.history['acc'])
# plt.xlabel(['Epochcount'])
# plt.plot(training.history['val_acc'])
# plt.ylabel(['Accuracy'])
# plt.show()
# plt.savefig('accuracy.png')
#
#
# plt.plot(training.history['loss'])
# plt.xlabel(['Epochcount'])
# plt.plot(training.history['val_loss'])
# plt.ylabel(['Lossdata'])
# plt.show()
# plt.savefig('loss.png')
#

